on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Publish package to hex.pm
        uses: CoderDennis/action-publish-hex@v1
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
